### PR TITLE
Add Jenkinsfile for ci.jenkins.io

### PR DESCRIPTION
**Pull request by SaarthakMaini**
Compile and test PR’s automatically

# Changes

Added a Jenkinsfile

# Submitter Checklist

- [X] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

According to the [Google Document](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#) provided , I have added a Jenkinsfile to this repository as it was missing one

# Release Notes

```
Jenkinsfile was added to Compile and Test PR's automatically

```

### CODE REVIEW

**Comment by brokenpip3** [comment]
Hi @SaarthakMaini thanks for your contribution, I took a quick look at the doc but correct me if I'm wrong this is necessary only for the jenkins plugins, this project does not contains a plugin, I'm missing something here?

**Comment by brokenpip3** [comment]
closed due to inactivity. Feel free to re-open it if you think will be necessary

**Comment by lemeurherve** [comment]
> Hi @SaarthakMaini thanks for your contribution, I took a quick look at the doc but correct me if I'm wrong this is necessary only for the jenkins plugins, this project does not contains a plugin, I'm missing something here?

@brokenpip3 for the record `buildPlugin` can be used to build any Maven project on ci.jenkins.io, not only plugins.

I think it would be beneficial to use it.

**Comment by brokenpip3** [comment]
I can merge it without any doubts but there is no maven project in this repo :)

**Comment by lemeurherve** [comment]
> I can merge it without any doubts but there is no maven project in this repo :)

My bad, I should have looked more closely 😅 

If you want we can add the necessary tools to build the different parts of this project on ci.jenkins.io though.

**Comment by lemeurherve** [comment]
Please don't merge, this might make all PRs fail as there would be nothing to build.
Building this project with ci.jenkins.io will require a custom Jenkinsfile, not one with `buildPlugin`.

**Comment by brokenpip3** [comment]
Understood I was convinced that if any jenskinsfile or maven project is present the ci.jenkins.io will skip this repo.
Will close this PR for the moment and re-open it if we are going to take advantage of ci.jenkins.io.

thanks for the insight

**Pull request closed without merging**
