### PR TITLE
Update go version from 1.13 to 1.14

### PR DESCRIPTION
**Pull request by Avni-Sharma**

### CODE REVIEW

**Comment by waveywaves** [comment]
@Avni-Sharma can you review this for failing tests ?

**Comment by akram** [comment]
@Avni-Sharma  you need to use an earlier version of staticcheck also: 2020.1.3 
it has to be changed in Makefile

**Comment by waveywaves** [comment]
Tested your branch

**Comment by waveywaves** [comment]
LGTM

**Comment by tomaszsek** [comment]
@Avni-Sharma One more place for update https://github.com/jenkinsci/kubernetes-operator/blob/master/config.base.env#L4

**Pull request closed without merging**
