### PR TITLE
Seed job SCM may now be configured with github-branch-source/GitHubAppCredentials

### LINKED ISSUE #614: Allow seed job scm to be configured with github-branch-source/GitHubAppCredentials
**Describe the solution you'd like**
I'd like for the operator to allow [`GitHubAppCredentials` type credentials](https://github.com/jenkinsci/github-branch-source-plugin/blob/923184ce70fc84252937b8d08872f666efcc288b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java) to configure the git SCM for seed jobs. This is already supported in the git SCM, i suppose because `GitHubAppCredentials` implements `StandardUsernamePasswordCredentials` ..but i'm not sure. I know i can update the credentials on the operator-created seed job ( with no other changes ) and scan and checkout will both work.

**Describe alternatives you've considered**
Moving away from personal access tokens to github apps, there isn't an alternative it seems: I currently configure the seed job with an app client secret ( username + password ) that validates in the operator but fails to authenticate at scan-time. I log in to the UI, update the seed job credential to the `GitHubAppCredentials` one ( appid + private key ) and everything works.

### PR DESCRIPTION
**Pull request by andlaz**
# Changes

resolves #614 

# Submitter Checklist

- [x] Includes tests (if functionality changed/added)
- [x] Includes docs (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

## Reviewer Notes

# Release Notes

### CODE REVIEW

**Comment by andlaz** [comment]
i could use some hints as to, where i need to make a change in e2e tests to make this pass please? It's indirectly an API change because of the extension of CR validation to allow the use of GitHubAppCredentials in the seedJobs array

**Comment by Sig00rd** [comment]
Hi @andlaz and thanks for contributing this, could you also add some test cases for validating this credential type in https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/user/seedjobs/validate_test.go ?

**Review by prryb — APPROVED** [review]

**Review by MKajzik — APPROVED** [review]

**Review by thecooldrop — APPROVED** [review]

**Comment by andlaz** [comment]
Could this please be merged?

**Comment by mario21ic** [comment]
this is the PR that I just need.
could somebody merge this PR? 🙏

**Comment by Sig00rd** [comment]
Sorry for the delay!

**Pull request merged**
