### PR TITLE
Externalize hardcoded image uid and pod Security Context and removes default Command

### PR DESCRIPTION
**Pull request by akram**
Hi team,

this PR is intended to improve reusability of the Jenkins operator. With the current code, the image UID is hardcoded in the controller and has to SecurityContext.runAsUser to be run. This causes some issues in environments with more strict SecurityContextConstraints.

Also, the example Jenkins CR has been provided to show how one can override the default "Command" which is also kind of hardcoded in the controller.

### CODE REVIEW

**Comment by akram** [comment]
@codem8s can yo PTAL ?

**Comment by tomaszsek** [comment]
Hi @akram,

I agree that SecurityContext should be parameterized. `/var/jenkins/scripts/init.sh` is provided by the operator to configure init.groovy.d and scripts, install plugins and run Jenkins.
If we give ability to configure command for the Jenkins container the operator will loose control over these configurations. 

Cheers

**Comment by akram** [comment]
> Hi @akram,
> 
> I agree that SecurityContext should be parameterized. `/var/jenkins/scripts/init.sh` is provided by the operator to configure init.groovy.d and scripts, install plugins and run Jenkins.
> If we give ability to configure command for the Jenkins container the operator will loose control over these configurations.
> 
> Cheers

What about using an init container instead ? That way, we could be sure that some initialisation process will always occur (do the minimum wiring with the operator mechanics), and we give the ability to end user to customise its own startup process.

**Comment by tomaszsek** [comment]
Why do you want to override Jenkins startup process?

**Comment by akram** [comment]
I actually already have existing Jenkins CI Server images (with a specific startup process), and I want the Jenkins Operator to be able to deploy them. I would guess that other users may also have their own images.

**Comment by tomaszsek** [comment]
@akram These changes are included in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.1.1 release.

**Pull request merged**
