### PR TITLE
'make run' picks up current-context instead of minikube as default

### PR DESCRIPTION
**Pull request by waveywaves**
fixes https://github.com/jenkinsci/kubernetes-operator/issues/219

Currently running `make run` sets context as minikube which is not advised, instead, it should use the current-context if a context is not already set.

### CODE REVIEW

**Comment by jakalkhalili** [comment]
LGTM, what do you think @tomaszsek

**Comment by tomaszsek** [comment]
@waveywaves I think it is already fixed but in the `openshift` branch https://github.com/jenkinsci/kubernetes-operator/blob/openshift/Makefile.

**Comment by waveywaves** [comment]
@tomaszsek this is not Openshift specific. Just an update to the makefile to make developers easily test the operator on a local cluster. Will update do a accordingly as well if that is necessary.

**Comment by pawelprazak** [comment]
@tomaszsek it's not in openshift branch, I've just checked

**Comment by pawelprazak** [comment]
On the other thought, I'm afraid that taking current context would be error prone for some workflows.

E.g. I always use explicit kubectl context and I don't even know what is my current default but I'm sure it is not the cluster I would want to use.

**Comment by pawelprazak** [comment]
@waveywaves, @tomaszsek showed me this line:
https://github.com/jenkinsci/kubernetes-operator/blob/9b4a04c32f6171fc65dd8852695457a19de7abe8/Makefile#L166

it sets the kubectl context depending on the config used

**Comment by waveywaves** [comment]
Screenshot from 2019-12-19 19-09-44
@pawelprazak @tomaszsek Thanks  for letting me know on that one. I missed that bit. After checking it now, seems like deploy/namespace-init.yaml does not exist. 

https://github.com/jenkinsci/kubernetes-operator/blob/9b4a04c32f6171fc65dd8852695457a19de7abe8/Makefile#L166-L167
Based on the above it seems like KUBERNETES_PROVIDER is not used as a context because of which the context is still being taken as minikube.

**Comment by pawelprazak** [comment]
@waveywaves have you seen this?
https://github.com/jenkinsci/kubernetes-operator/blob/9b4a04c32f6171fc65dd8852695457a19de7abe8/website/content/en/docs/Getting%20Started/future/developer-guide.md#running-e2e-tests-on-linux

**Comment by pawelprazak** [comment]
and `deploy/namespace-init.yaml` is created in this line at runtime: https://github.com/jenkinsci/kubernetes-operator/blob/9b4a04c32f6171fc65dd8852695457a19de7abe8/Makefile#L172

**Pull request closed without merging**
