### PR TITLE
Add tolerations for jenkis pod

### PR DESCRIPTION
**Pull request by tombokombo**
# Changes
Add possibility to set tolerations for jenkins pod. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
- Add tolerations for jenkins pod in helm chart
```

### CODE REVIEW

**Comment by brokenpip3** [comment]
Hi @tombokombo to support the toleration in the result jenkins pod what you did is not enough you need to modify the go struct and the crds, you can check [this](https://github.com/jenkinsci/kubernetes-operator/pull/754) PR as example :)

**Comment by tombokombo** [comment]
Hi @brokenpip3 you are perfectly right but it's already there, in code 
https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/base/resources/pod.go#L383 
and CRD:
https://github.com/jenkinsci/kubernetes-operator/blob/master/chart/jenkins-operator/crds/jenkins-crd.yaml#L1329. 
Tt was just missing in chart. We are running this patched version in production. 
BTW behavior is same as nodeSelector, which means pod is not recreated after change of nodeSelector, tolerations and maybe other fields. I will take a look on this, but in another PR.

**Comment by brokenpip3** [comment]
Oh great! I was no aware that we already support that, perfect.
Thanks for your contribution!

**Review by brokenpip3 — APPROVED** [review]

**Comment by brokenpip3** [comment]
sorry @tombokombo I had to revert this because I need the master branch to be ci-happy so we can push nightly versions. I don't know why but this change broke one e2e test, I opened this to track and fix the issue: https://github.com/jenkinsci/kubernetes-operator/issues/808.
Will try to put the toleration back asap, sorry for the inconvenient.

**Pull request merged**
