### PR TITLE
generate openapi validation schema

### PR DESCRIPTION
**Pull request by sbose78**
Ran `operator-sdk generate openapi` to generate the same.

In a different PR, I could add it to `make build`, though I don't prefer generating code at build time.

### CODE REVIEW

**Comment by waveywaves** [comment]
```
$ travis_setup_go
gimme: given '1.13.x' but no release for '1.13' found
gimme: given '1.13.x' but no release for '1.13' found
Failed to run gimme
The command "travis_setup_go" failed and exited with 86 during .
```

This PR is dependent on https://github.com/jenkinsci/kubernetes-operator/pull/269 I suppose. @sbose78 can you confirm this ?

**Comment by sbose78** [comment]
Ideally, it shouldn't be. Could you help me understand the above issue, please?

**Comment by tomaszsek** [comment]
@sbose78 Please rebase with master because e2e tests didin't run. The fix for e2e test -  https://github.com/jenkinsci/kubernetes-operator/commit/018c8cc709ecc303a6e51b3b5699c6b047bfe318.

**Comment by sbose78** [comment]
done.

**Comment by tomaszsek** [comment]
@sbose78 Thanks :+1:

**Pull request merged**
