### PR TITLE
fix(doc): update jenkins plugins versions in doc

### PR DESCRIPTION
**Pull request by lemeurherve**
Follow-up of https://github.com/jenkinsci/kubernetes-operator/pull/670

# Changes

Update of the docs following this PR: https://github.com/jenkinsci/kubernetes-operator/pull/670

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes tests (if functionality changed/added)
- [X] Includes docs (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by lemeurherve** [comment]
In retrospect I'm wondering if I really had to also update the 0.5.x version...  
WDYT? Should I restore it?

**Comment by Sig00rd** [comment]
Hello @lemeurherve, sorry for the late response. I think you're right - could you restore the 0.5.x docs?

**Comment by lemeurherve** [comment]
@Sig00rd no problem, I've restored the 0.5.x docs

**Comment by Sig00rd** [comment]
@lemeurherve Great, thanks for the contribution!

**Review by Sig00rd — APPROVED** [review]

**Pull request merged**
