### PR TITLE
[WIP] Include jobs/*/config.xml for backups

### PR DESCRIPTION
**Pull request by pawelprazak**
For easier workarounds for #104 and #210 specifically.

This is the minimal change, but a better one would be to include it only for Multi-branch jobs/projects.

### CODE REVIEW

**Comment by tomaszsek** [comment]
We have to split backup:
- create tar as we did before in temporary directory
- loop over all jobs detects if it is multibranch and add the `config.xml` file to the tar(`tar -uf filename.tar new_file`)
- run `gzip` which will create compressed file `.tar.gz`

Don't forget to create the e2e test https://github.com/jenkinsci/kubernetes-operator/tree/master/backup/pvc/e2e.

**Comment by pbecotte** [comment]
What is the status of this? Anything that someone could help with?

**Comment by tomaszsek** [comment]
Hi @pbecotte,

If you have spare time you can help us with this improvement. If don't please tell us and we will try the best to do it for you.

Cheers

**Comment by pbecotte** [comment]
Sure, but not sure what its waiting on. The items from your comment from Nov 26?

**Comment by tomaszsek** [comment]
Yes, feel free to create another PR and follow the instructions from this comment https://github.com/jenkinsci/kubernetes-operator/pull/211#issuecomment-558574782.

**Comment by pniederlag** [comment]
Just for the records: this has been fixed in v0.0.8 PVC backup provider. Thx!

**Pull request closed without merging**
