### PR TITLE
Patching vulnerabilities

### PR DESCRIPTION
**Pull request by Rickyf115**
# Changes

Patching some Critical and High vulnerabilities as identified from a Prisma scan

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

### CODE REVIEW

**Comment by Rickyf115** [comment]
We probably need to update the github environment to build off golang 1.21.4 to get these tests happy

**Comment by Rickyf115** [comment]
Wanted to also update controller-util but unsure of what backwards compatibility we're aiming for here, as well as I didn't want to mess up reporting for testing, probably something to be done in the near future though, this is 9 minor versions behind

**Comment by brokenpip3** [comment]
Thanks for your PR however you can't update a project like this by just updating the go mod and the go version.

First of all a lot of golang code will result not functional after an upgrade like this.
Second: this project is based on operator-sdk that is based on kubebuilder, you need to follow the upgrade sdk instruction: https://sdk.operatorframework.io/docs/upgrading-sdk-version/ version by version and fix all the go code after. Not mentioning the tests part.

I'm already working on that on branch called `version-9.0` and this is the operator-sdk update (now is already old I guess): https://github.com/jenkinsci/kubernetes-operator/commit/a76d38031090d131c7fdd744f3abda8910d349a5 but for the moment I was not able to find the appropriate time needed during an holiday or similar to complete the task.

**Comment by Rickyf115** [comment]
Closing and will watch for your v9 update

**Comment by brokenpip3** [comment]
sure, I wish I can have more time to dedicate on this milestone but it's not something I can do atm, not before the next year at least

**Pull request closed without merging**
