### PR TITLE
Fix GVK Parsng and restore Types in Schema

### PR DESCRIPTION
**Pull request by waveywaves**
# Changes

This reverts commit 445cf2eb8c498b015eab2c867a52b00420f8037b.
The commit that is being reverted back as the operator is not able to create Routes or Deployments because these schemes arent registered with the Operator.

```
2020-06-13T19:57:38.569+0530    INFO    controller-jenkins      jenkins/handler.go:88   *v1alpha2.Jenkins/jenkins has been updated   {"cr": "jenkins"}                             
2020-06-13T19:57:42.907+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}
2020-06-13T19:57:46.188+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}
2020-06-13T19:57:50.385+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}
2020-06-13T19:57:54.078+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}
2020-06-13T19:57:57.551+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}

```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by waveywaves** [comment]
cc @tomaszsek @akram @jkhelil

**Comment by tomaszsek** [comment]
You change cause the same issue as described here https://github.com/operator-framework/operator-sdk/issues/2577. Just run one of the e2e tests and look at the operator logs.

**Comment by waveywaves** [comment]
@tomaszsek Even if it does cause the same issue, the operator breaks when you remove those schemes. It is not able to create the resources when you remove those schemes. 

Removing this schemas is not going to solve the issue of these error but is defnitely breaking the operator. Please check https://github.com/operator-framework/operator-sdk/issues/2577#issuecomment-591347654 where the workaround for this is provided which can be seen in this commit https://github.com/3scale/3scale-operator/commit/df49604d9fd3875a345a84b0e63f0ac7a08d25f7. 

Those are the changes we need to make and not remove the Schemas.

**Comment by waveywaves** [comment]
Let me update this PR to have those changes added

**Comment by waveywaves** [comment]
@tomaszsek Can you PTAL ?

**Pull request merged**
