### PR TITLE
fix(master): pass lifecycle configuration to master container

### PR DESCRIPTION
**Pull request by DionJones615**
# Changes

Simply passed the lifecycle defined in the Jenkins CRD down to the generated pod definition. The necessary bits appear to already be in the CRD.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by brokenpip3** [comment]
ehi @DionJones615 thanks for your contribution.

I think here we miss:
- a guard if lifecycle is empty
- the option listed in the helm chart values and jenkins template

wdyt? 

thanks

**Comment by DionJones615** [comment]
@brokenpip3 Sorry, priorities shifted for a minute. :) How's this looking?  Working well in my tests

**Comment by brokenpip3** [comment]
Nice, ty for coming back and try to complete the PR!

did you tried locally with a binary build from this PR to pass a lifecycle? I wish we can add a test, at least [here](https://github.com/jenkinsci/kubernetes-operator/blob/a4fa09b2edec87e5b1fa14d461f8c5ab03fc9263/test/bats/2-deploy-with-more-options.bats#L26-L36). If everything is green after that we can merge it :)

**Review by brokenpip3 — APPROVED** [review]
perfect, thanks for your contribution!

**Pull request merged**
