### PR TITLE
Customize jenkins-operator helmchart with adding 'hostAliases'

### PR DESCRIPTION
**Pull request by ywang-psee**
# Changes
add 'hostAliases' item into jenkins-operator helmchart.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by ywang-psee** [comment]
@Sig00rd @prryb

**Review by thecooldrop — APPROVED** [review]
LGTM

**Comment by ywang-psee** [comment]
Hi, can you please approval this pull request if the change is ok for you please? @Sig00rd @prryb. Thanks!

**Comment by prryb** [comment]
Hey, looks like a similar PR is already merged in: https://github.com/jenkinsci/kubernetes-operator/pull/720. Closing this one.

**Pull request closed without merging**
