### PR TITLE
Update and Sort Base Plugins

### PR DESCRIPTION
**Pull request by tveal**
Ran into problems setting newer versions of plugins in the jenkins *instance* yaml than the versions in `base_plugins.go`. For maintenance and consistency, I moved all the single-use plugin versions to the same `const` declaration as the other versions and sorted them. Also added a bash script (plenty of room for improvement) to help checking for newer versions.

I'd really like the jenkins-operator to allow specifying newer versions of base plugins in the *instance* yaml. Especially if you have a team that uses one operator in a given namespace, but multiple instances of Jenkins in the same namespace.

Script output before updating the plugins:
```
PLUGIN ID                               LOCAL VERSION  LATEST                          NEW PLUGIN:VERSION
ace-editor                              1.1            1.1                             ace-editor:1.1
apache-httpcomponents-client-4-api      4.5.5-3.0      4.5.5-3.0                       apache-httpcomponents-client-4-api:4.5.5-3.0
authentication-tokens                   1.3            1.3                             authentication-tokens:1.3
branch-api                              2.1.2          2.5.1          UPDATE AVAILABLE branch-api:2.5.1
cloudbees-folder                        6.7            6.8            UPDATE AVAILABLE cloudbees-folder:6.8
configuration-as-code                   1.7            1.16           UPDATE AVAILABLE configuration-as-code:1.16
configuration-as-code-support           1.7            1.16           UPDATE AVAILABLE configuration-as-code-support:1.16
credentials-binding                     1.18           1.18                            credentials-binding:1.18
credentials                             2.1.18         2.1.19         UPDATE AVAILABLE credentials:2.1.19
display-url-api                         2.3.0          2.3.1          UPDATE AVAILABLE display-url-api:2.3.1
docker-commons                          1.13           1.15           UPDATE AVAILABLE docker-commons:1.15
docker-workflow                         1.17           1.18           UPDATE AVAILABLE docker-workflow:1.18
durable-task                            1.29           1.29                            durable-task:1.29
git-client                              2.7.6          2.7.7          UPDATE AVAILABLE git-client:2.7.7
git                                     3.9.3          3.10.0         UPDATE AVAILABLE git:3.10.0
git-server                              1.7            1.7                             git-server:1.7
handlebars                              1.1.1          1.1.1                           handlebars:1.1.1
jackson2-api                            2.9.8          2.9.9          UPDATE AVAILABLE jackson2-api:2.9.9
job-dsl                                 1.72           1.74           UPDATE AVAILABLE job-dsl:1.74
jquery-detached                         1.2.1          1.2.1                           jquery-detached:1.2.1
jsch                                    0.1.55         0.1.55                          jsch:0.1.55
junit                                   1.27           1.28           UPDATE AVAILABLE junit:1.28
kubernetes-credentials                  0.4.0          0.4.0                           kubernetes-credentials:0.4.0
kubernetes-credentials-provider         0.12.1         0.12.1                          kubernetes-credentials-provider:0.12.1
kubernetes                              1.14.8         1.15.5         UPDATE AVAILABLE kubernetes:1.15.5
lockable-resources                      2.4            2.5            UPDATE AVAILABLE lockable-resources:2.5
mailer                                  1.23           1.23                            mailer:1.23
matrix-project                          1.14           1.14                            matrix-project:1.14
momentjs                                1.1.1          1.1.1                           momentjs:1.1.1
pipeline-build-step                     2.7            2.9            UPDATE AVAILABLE pipeline-build-step:2.9
pipeline-graph-analysis                 1.9            1.10           UPDATE AVAILABLE pipeline-graph-analysis:1.10
pipeline-input-step                     2.9            2.10           UPDATE AVAILABLE pipeline-input-step:2.10
pipeline-milestone-step                 1.3.1          1.3.1                           pipeline-milestone-step:1.3.1
pipeline-model-api                      1.3.6          1.3.8          UPDATE AVAILABLE pipeline-model-api:1.3.8
pipeline-model-declarative-agent        1.1.1          1.1.1                           pipeline-model-declarative-agent:1.1.1
pipeline-model-definition               1.3.6          1.3.8          UPDATE AVAILABLE pipeline-model-definition:1.3.8
pipeline-model-extensions               1.3.6          1.3.8          UPDATE AVAILABLE pipeline-model-extensions:1.3.8
pipeline-rest-api                       2.10           2.11           UPDATE AVAILABLE pipeline-rest-api:2.11
pipeline-stage-step                     2.3            2.3                             pipeline-stage-step:2.3
pipeline-stage-tags-metadata            1.3.6          1.3.8          UPDATE AVAILABLE pipeline-stage-tags-metadata:1.3.8
pipeline-stage-view                     2.10           2.11           UPDATE AVAILABLE pipeline-stage-view:2.11
plain-credentials                       1.5            1.5                             plain-credentials:1.5
scm-api                                 2.3.0          2.4.1          UPDATE AVAILABLE scm-api:2.4.1
script-security                         1.54           1.59           UPDATE AVAILABLE script-security:1.59
ssh-credentials                         1.15           1.16           UPDATE AVAILABLE ssh-credentials:1.16
structs                                 1.17           1.19           UPDATE AVAILABLE structs:1.19
variant                                 1.2            1.2                             variant:1.2
workflow-aggregator                     2.6            2.6                             workflow-aggregator:2.6
workflow-api                            2.33           2.34           UPDATE AVAILABLE workflow-api:2.34
workflow-basic-steps                    2.14           2.16           UPDATE AVAILABLE workflow-basic-steps:2.16
workflow-cps-global-lib                 2.13           2.13                            workflow-cps-global-lib:2.13
workflow-cps                            2.64           2.68           UPDATE AVAILABLE workflow-cps:2.68
workflow-durable-task-step              2.29           2.30           UPDATE AVAILABLE workflow-durable-task-step:2.30
workflow-job                            2.32           2.32                            workflow-job:2.32
workflow-multibranch                    2.21           2.21                            workflow-multibranch:2.21
workflow-scm-step                       2.7            2.7                             workflow-scm-step:2.7
workflow-step-api                       2.19           2.19                            workflow-step-api:2.19
workflow-support                        3.2            3.3            UPDATE AVAILABLE workflow-support:3.3
```

### CODE REVIEW

**Comment by tomaszsek** [comment]
@tveal Thanks for the first pull request 😎
You can override plugins required by operator in CR 'spec.master.basePlugins'. I thought about mechanism which will automatically bump Jenkins plugins make e2e tests and maybe release new version.

**Comment by tveal** [comment]
> @tveal Thanks for the first pull request 
> You can override plugins required by operator in CR 'spec.master.basePlugins'. I thought about mechanism which will automatically bump Jenkins plugins make e2e tests and maybe release new version.

@tomaszsek  Oh sweet! I didn't catch that before. Auto-bumping base plugin versions would be very nice :)
My Golang skills aren't great at this time, so I wouldn't be much help :(
This is my first pull request on GitHub and first outside of a corporate setting.

I'm also following another thread related to this project, trying to pass the jenkins-operator secret to a SecurityRealm plugin via CasC. I see how to do it in the user's config secret, but is there a way to get the operator's credential secret into the user's ConfigMap? The goal is to get the generated operator password into the _instantiation_ of a SecurityRealm plugin as a `roboticPassword`, so that future requests to the Jenkins master can be authenticated in the SecurityRealm plugin. Such as `instantiationRoboticPassword == currentPassword` (and user for that matter, but it appears to always be `jenkins-operator`). Since the operator cred is re-generated at times, I need the update to the operator's secret to also be refreshed in the user's ConfigMap. Any ideas? Should I create a new issue for this topic?

**Comment by tomaszsek** [comment]
> I'm also following another thread related to this project, trying to pass the jenkins-operator secret to a SecurityRealm plugin via CasC. I see how to do it in the user's config secret, but is there a way to get the operator's credential secret into the user's ConfigMap? The goal is to get the generated operator password into the instantiation of a SecurityRealm plugin as a roboticPassword, so that future requests to the Jenkins master can be authenticated in the SecurityRealm plugin. Such as instantiationRoboticPassword == currentPassword (and user for that matter, but it appears to always be jenkins-operator). Since the operator cred is re-generated at times, I need the update to the operator's secret to also be refreshed in the user's ConfigMap. Any ideas? Should I create a new issue for this topic?

@tveal Please create new issue for that usecase. Could you provide plugin for SecurityRealm and maybe CasC code?

**Comment by tveal** [comment]
> @tveal Please create new issue for that usecase. Could you provide plugin for SecurityRealm and maybe CasC code?

@tomaszsek Created Issue #19

**Pull request merged**
