### PR TITLE
Combine dark and regular logo in README.md

### PR DESCRIPTION
**Pull request by pyatizbyantsevia**
# Changes

Since the paths between the repositories to assets/ are different, the working version can be viewed on the master branch of my [fork](https://github.com/pyatizbyantsevia/kubernetes-operator).

It might be worth creating a logo in .svg format so as not to have 2 files and encapsulate all the logic inside the svg, as in [design-library-plugin](https://github.com/jenkinsci/design-library-plugin/pull/263)

To check the functionality, you can open two tabs: [master branch in my fork](https://github.com/pyatizbyantsevia/kubernetes-operator/tree/master), [appearance settings](https://github.com/settings/appearance). By switching the style on the appearance tab and then refreshing the fork page, you can see the functionality

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by pyatizbyantsevia** [comment]
If this PR is accepted, then before the merge I would be very grateful if there was a label for Hacktoberfest (hactoberfest-accepted)

**Comment by pyatizbyantsevia** [comment]
@brokenpip3, could you take a look?

**Comment by brokenpip3** [comment]
Yes, sorry will take a look during this week

**Review by brokenpip3 — APPROVED** [review]

**Comment by brokenpip3** [comment]
thanks for your contribution

**Comment by pyatizbyantsevia** [comment]
Thank you! Sorry, I made a mistake in the label name, it should be "hacktoberfest-accepted", missed the 'k'.
Thanks again!

**Comment by brokenpip3** [comment]
done

**Pull request merged**
